default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tattletale_development
test:
  <<: *default
  database: tattletale_test
production:
  <<: *default
  database: tattletale_production
  username: tattletale
  password: <%= ENV['TATTLETALE_DATABASE_PASSWORD'] %>
